#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create the restricted application user
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    
    -- Create the test database
    CREATE DATABASE $POSTGRES_TEST_DB;
    
    -- Grant privileges
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $APP_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_TEST_DB TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_TEST_DB TO $APP_USER;
EOSQL