"""Refactor to use shared mixins

Revision ID: 19a1219e525e
Revises: d99451053c8c
Create Date: 2026-03-28 14:22:26.595226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a1219e525e'
down_revision: Union[str, Sequence[str], None] = 'd99451053c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_constraint(op.f('tenants_name_key'), 'tenants', type_='unique')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_unique_constraint(op.f('tenants_name_key'), 'tenants', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    # ### end Alembic commands ###
